# Bonus Task: 
# Scenario: 
# An online shopping company wants to analyze its sales data to understand customer 
# purchasing behavior, product performance, and city-wise sales trends.  
# You are hired as a Data Analyst to perform data analysis using NumPy and Pandas in 
# Python. 
# The company has provided a CSV file named: online_store_sales_data.csv 
# You are required to: 
# 1. Load the CSV file using Pandas. 
# 2. Display: 
# • First 5 records 
# • Last 3 records 
# • Dataset information 
# • Summary statistics 
# 3. Create a new column: Total_Amount = Quantity × Price_Per_Unit 
# 4. Find: 
# • Total revenue generated by the store 
# • Product with highest sales 
# • City with maximum orders 
# • Average price of products 
# 5. Display: 
# • Orders where Total_Amount is greater than 50,000 
# • Customers who purchased laptops 
# 6. Sort the dataset: 
# • By Quantity in descending order 
# • By Price_Per_Unit in ascending order 
# 7. Use NumPy to calculate: 
# • Average quantity sold 
# • Maximum quantity sold 
# • Minimum quantity sold 
# 8. Save the updated dataset into a new CSV file named: 
# updated_sales_report.csv 
# 9. Create a bar chart showing total sales of each product


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Load the CSV file
# df = pd.read_csv('online_store_sales_data.csv')
df = pd.read_csv(r"D:\University Content and lab (4)\ACP Python\assignment04\online_store_sales_data.csv")
print("First 5 records:")
print(df.head())
print("Last 3 records:")
print(df.tail(3))
print("Dataset information:")
print(df.info())
print("Summary statistics:")
print(df.describe())

df['Total_Amount'] = df['Quantity'] * df['Price_Per_Unit']
totalRevenue = df['Total_Amount'].sum()
print("Total revenue generated by the store: ", totalRevenue)
productWithHighestSales = df.groupby('Product')['Total_Amount'].sum().idxmax()
print("Product with highest sales: ", productWithHighestSales)
cityWithMaxOrders = df['City'].value_counts().idxmax()
print("City with maximum orders: ", cityWithMaxOrders)
averagePrice = df['Price_Per_Unit'].mean()
print("Average price of products: ", averagePrice)
ordersGreaterThan50000 = df[df['Total_Amount'] > 50000]
print("Orders where Total_Amount is greater than 50,000:")
print(ordersGreaterThan50000)
customersWhoPurchasedLaptops = df[df['Product'] == 'Laptop']['Customer_Name'].unique()
print("Customers who purchased laptops: ", customersWhoPurchasedLaptops)
sortedByQuantity = df.sort_values(by='Quantity', ascending=False)
print("Dataset sorted by Quantity in descending order:")
print(sortedByQuantity)
sortedByPrice = df.sort_values(by='Price_Per_Unit', ascending=True)
print("Dataset sorted by Price_Per_Unit in ascending order:")
print(sortedByPrice)



averageQuantity = np.mean(df['Quantity'])
print("Average quantity sold: ", averageQuantity)
maxQuantity = np.max(df['Quantity'])
print("Maximum quantity sold: ", maxQuantity)
minQuantity = np.min(df['Quantity'])
print("Minimum quantity sold: ", minQuantity)
df.to_csv('updated_sales_report.csv', index=False)
salesByProduct = df.groupby('Product')['Total_Amount'].sum()
salesByProduct.plot(kind='bar')

plt.xlabel('Product')
plt.ylabel('Total Sales')
plt.title('Total Sales of Each Product')
plt.show()


